"use client";
import { useEffect, useState, type FormEvent } from "react";
import Link from "next/link";
import { api } from "../lib/client";
import type { Dataset, OrderPage } from "../lib/contracts";
import { errorText, quantity } from "../lib/presentation";
import { Badge, ErrorBox, Loading, Shell } from "./ui";
import { portfolioDemo } from "../lib/mode";

export function Dashboard({ initialDataset = "" }: { initialDataset?: string }) {
  const [data, setData] = useState<Dataset[] | null>(null), [error, setError] = useState("");
  const [selected, setSelected] = useState(initialDataset), [retry, setRetry] = useState(0);
  useEffect(() => { const abort = new AbortController(); api.datasets(abort.signal).then(setData).catch(e => { if (!abort.signal.aborted) setError(errorText(e)); }); return () => abort.abort(); }, [retry]);
  const ready = data?.filter(d => d.status === "READY") ?? [];
  const dataset = ready.find(d => d.dataset_version_id === (selected || (ready.length === 1 ? ready[0].dataset_version_id : "")));
  return <Shell><main><div className="page-heading"><div><div className="eyebrow">PROCUREMENT INTELLIGENCE</div><h1>Overdue PO Copilot</h1><p>超期采购订单智能诊断与决策系统 · 从数据到下一步。</p></div><label className="dataset-picker">业务数据集<select aria-label="业务数据集" value={dataset?.dataset_version_id ?? ""} onChange={e => setSelected(e.target.value)}><option value="">请选择 READY 数据集</option>{ready.map(d => <option key={d.dataset_version_id} value={d.dataset_version_id}>{d.dataset_version_name} · {d.snapshot_date}</option>)}</select></label></div>{error ? <ErrorBox message={error} retry={() => { setError(""); setRetry(n => n + 1); }} /> : !data ? <Loading /> : !ready.length ? <div className="empty">暂无 READY 数据集。请先启动 System A 并准备已完成的数据集。</div> : !dataset ? <div className="empty">请选择一个明确的数据集，开始查看超期订单。</div> : <OrderWorkspace key={dataset.dataset_version_id} dataset={dataset} />}</main></Shell>;
}
function OrderWorkspace({ dataset }: { dataset: Dataset }) {
  const [filters, setFilters] = useState<Record<string, string>>({}), [page, setPage] = useState(1);
  function filter(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const values = new FormData(event.currentTarget); setFilters(Object.fromEntries([...values.entries()].map(([key, value]) => [key, String(value).trim()]).filter(([,value]) => value))); setPage(1); }
  return <><div className="context-bar"><span className="dot" /> Snapshot <strong>{dataset.snapshot_date}</strong><span>{portfolioDemo ? "已验收合成快照 · 列表页未逐行重算" : "全部数据来自公开报表 · 未运行逐行诊断"}</span></div><section className="panel order-panel"><div className="section-heading"><div><h2>超期订单清单</h2><p>先定位订单，再进入完整诊断与决策。</p></div><span className="table-source">{portfolioDemo ? "BUNDLED SYSTEM A SNAPSHOT" : "SYSTEM A / REPORT 1"}</span></div><form className="filter-form" onSubmit={filter}><label>PO 号<input name="po_number" placeholder="输入 PO 号" maxLength={120} /></label><label>物料编码<input name="material_code" placeholder="输入物料编码" maxLength={120} /></label><label>供应商<input name="supplier" placeholder="名称或编码" maxLength={120} /></label><label>参考项目<input name="project" placeholder="项目名称或编码" maxLength={120} /></label><button className="primary" type="submit">筛选订单</button><button className="text-button" type="reset" onClick={() => { setFilters({}); setPage(1); }}>重置</button></form><OrderList key={JSON.stringify([filters,page])} dataset={dataset} filters={filters} page={page} setPage={setPage} /></section><div className="workflow"><div><span>01</span><h3>查看确定性指标</h3><p>固定业务日期，区分零值与不可计算。</p></div><div><span>02</span><h3>了解原因与处置</h3><p>业务规则产生结论，缺证据时保持未决。</p></div><div><span>03</span><h3>向 Copilot 追问</h3><p>带上订单上下文，用中文获取有据回答。</p></div></div></>;
}
function OrderList({ dataset, filters, page, setPage }: { dataset: Dataset; filters: Record<string,string>; page: number; setPage: (page: number) => void }) {
  const [data, setData] = useState<OrderPage | null>(null), [error,setError] = useState(""), [retry,setRetry] = useState(0);
  useEffect(() => { const abort = new AbortController(); api.orders(dataset.dataset_version_id, { ...filters, page: String(page), page_size: "12" }, abort.signal).then(p => { if (p.snapshot_date !== dataset.snapshot_date) throw new Error("INVALID_RESPONSE"); setData(p); }).catch(e => { if (!abort.signal.aborted) setError(errorText(e)); }); return () => abort.abort(); }, [dataset, filters, page, retry]);
  if (error) return <ErrorBox message={error} retry={() => { setError(""); setRetry(n => n + 1); }} />;
  if (!data) return <Loading text="正在加载订单与报表统计…" />;
  const distinct = (field: "material_id" | "supplier_id" | "po_reference_project_id") => new Set(data.items.map(r => r[field]).filter(Boolean)).size;
  return <><div className="kpi-grid"><div><span>超期发运行</span><strong>{quantity(data.total)}</strong><small>当前筛选 · 非 PO Header 数</small></div><div><span>涉及物料</span><strong>{distinct("material_id")}</strong><small>本页 · 已知稳定 ID 去重</small></div><div><span>涉及供应商</span><strong>{distinct("supplier_id")}</strong><small>本页 · 已知稳定 ID 去重</small></div><div><span>参考项目</span><strong>{distinct("po_reference_project_id")}</strong><small>本页 · 不代表责任项目</small></div></div>{!data.items.length ? <div className="empty"><h3>没有匹配的超期订单</h3><p>尝试清空筛选条件，或选择其他数据集。</p></div> : <div className="table-scroll"><table><thead><tr><th>PO / 行 / 发运</th><th>物料</th><th>供应商 / 参考项目</th><th>库存组织</th><th>下单日期</th><th className="numeric">开放数量</th><th className="numeric">越界天数</th><th>订单状态</th><th><span className="sr-only">操作</span></th></tr></thead><tbody>{data.items.map((row,i) => <tr key={row.po_line_schedule_id ?? i}><td>{row.po_line_schedule_id ? <Link className="po-link" href={`/po?schedule=${row.po_line_schedule_id}&dataset=${dataset.dataset_version_id}`}>{row.po_number}</Link> : row.po_number}<small>行 {row.po_line_number} / 发运 {row.shipment_number}</small></td><td><strong>{row.material_code}</strong><small>{row.material_description ?? "未提供描述"}</small></td><td>{row.supplier_name}<small>{row.reference_project_name ?? "未提供参考项目"}</small></td><td>{row.inventory_organization_code}<small>{row.inventory_organization_type}</small></td><td className="nowrap">{row.order_date}</td><td className="numeric">{quantity(row.overdue_open_qty)}</td><td className="numeric"><span className="aging-number">+{row.overdue_days}</span> <small className="inline">天</small></td><td><Badge code={row.po_status} /></td><td>{row.po_line_schedule_id ? <Link className="row-action" aria-label={`分析 ${row.po_number} 行 ${row.po_line_number} 发运 ${row.shipment_number}`} href={`/po?schedule=${row.po_line_schedule_id}&dataset=${dataset.dataset_version_id}`}>分析 ↗</Link> : <span>身份缺失</span>}</td></tr>)}</tbody></table></div>}<div className="pagination"><span>第 {data.page} 页 · 共 {Math.max(1, Math.ceil(data.total / data.page_size))} 页 · 每页 {data.page_size} 条</span><div><button className="secondary" disabled={page <= 1} onClick={() => setPage(page - 1)}>← 上一页</button><button className="secondary" disabled={page * data.page_size >= data.total} onClick={() => setPage(page + 1)}>下一页 →</button></div></div><p className="table-footnote">数量沿用上游单位；清单保留源报表中的已关闭 / 零开放量记录，不在前端重判超期资格。</p></>;
}
