"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { api } from "../lib/client";
import type { CopilotResult, Order, QueryContext } from "../lib/contracts";
import { errorText, quantity } from "../lib/presentation";
import { Badge, ErrorBox, Evidence, Loading, MetricCard, ResultCards, Shell } from "./ui";
import { Copilot } from "./copilot";
export function Detail({ scheduleId, datasetId }: { scheduleId: string; datasetId: string }) {
  const [record,setRecord] = useState<{ order: Order; snapshot: string } | null>(null), [error,setError] = useState(""), [retry,setRetry] = useState(0);
  useEffect(() => { if (!datasetId) return; const abort = new AbortController(); Promise.all([api.orders(datasetId, { po_line_schedule_id: scheduleId }, abort.signal), api.datasets(abort.signal)]).then(([page, datasets]) => {
    const dataset = datasets.find(d => d.dataset_version_id === datasetId && d.status === "READY");
    if (!dataset || page.snapshot_date !== dataset.snapshot_date) throw new Error("INVALID_RESPONSE");
    if (page.total !== 1 || page.items.length !== 1 || page.items[0].po_line_schedule_id !== scheduleId) throw new Error("NOT_FOUND");
    setRecord({ order: page.items[0], snapshot: page.snapshot_date });
  }).catch(e => { if (!abort.signal.aborted) setError(errorText(e)); }); return () => abort.abort(); }, [datasetId,scheduleId,retry]);
  return <Shell detail><main><Link className="back-link" href={`/?dataset=${encodeURIComponent(datasetId)}`}>← 返回超期订单工作台</Link>{!datasetId ? <div className="empty">缺少 dataset 上下文，请从工作台选择订单。不会自动切换数据集。</div> : error ? <ErrorBox message={error} retry={() => { setError(""); setRetry(n => n + 1); }} /> : !record ? <Loading text="正在定位订单身份与业务快照…" /> : <Analysis key={`${datasetId}:${scheduleId}:${record.snapshot}`} order={record.order} context={{ dataset_version_id: datasetId, snapshot_date: record.snapshot, po_line_schedule_id: scheduleId }} />}</main></Shell>;
}
function Analysis({ order, context }: { order: Order; context: QueryContext }) {
  const [result,setResult] = useState<CopilotResult | null>(null), [error,setError] = useState(""), [retry,setRetry] = useState(0);
  useEffect(() => { const abort = new AbortController(); api.query(context, "请完整分析当前超期 PO 的指标、原因与建议动作。", abort.signal).then(setResult).catch(e => { if (!abort.signal.aborted) setError(errorText(e)); }); return () => abort.abort(); }, [context,retry]);
  return <><div className="page-heading detail-heading"><div><div className="eyebrow">ORDER INTELLIGENCE / 订单分析</div><h1>{order.po_number}<span>行 {order.po_line_number} / 发运 {order.shipment_number}</span></h1><p>{order.material_code} <span className="slash">/</span> {order.material_description ?? "未提供描述"}</p></div><div className="detail-status"><Badge code={result?.status ?? order.po_status} /><small>业务快照 {context.snapshot_date}</small></div></div><div className="detail-grid"><div className="analysis-column"><section className="panel overview"><div className="section-heading"><h2>订单概览 <small>PO OVERVIEW</small></h2><Badge code={order.po_status} /></div><dl>{[["供应商",order.supplier_name],["库存组织",`${order.inventory_organization_code} · ${order.inventory_organization_type}`],["参考项目",order.reference_project_name ?? "未提供"],["下单日期",order.order_date],["物料 LT",`${order.material_lt_days} 天`],["开放数量",quantity(order.overdue_open_qty)]].map(([key,value]) => <div key={key}><dt>{key}</dt><dd>{value}</dd></div>)}</dl></section><nav className="section-nav" aria-label="分析区域"><a href="#analytics">指标 Analytics</a><a href="#diagnosis">诊断 Diagnosis</a><a href="#decision">处置 Decision</a><a href="#evidence">证据 Evidence</a></nav>{error ? <ErrorBox message={error} retry={() => { setError(""); setResult(null); setRetry(n => n + 1); }} /> : !result ? <div className="panel"><Loading text="正在执行 Analytics → Diagnosis → Decision…" /><p className="contract-note">完整分析只在打开当前订单时运行，首页不逐行调用 Agent。</p></div> : <><section className="panel" id="analytics"><div className="section-heading"><div><span className="eyebrow">01 / ANALYTICS</span><h2>关键采购指标</h2></div><span className="table-source">后端确定性计算</span></div>{result.key_metrics.length ? <div className="analytics-grid">{result.key_metrics.map(metric => <MetricCard key={metric.name} metric={metric} />)}</div> : <div className="notice">当前分析尚未返回可展示指标。{result.status === "FAILED" && "请确认数据服务可用后重试。"}</div>}<p className="contract-note">Forecast change / inventory coverage / supply-demand：当前 Copilot 公开投影未提供，前端不补算。数量沿用上游原始单位。</p></section><ResultCards result={result} /><Evidence result={result} snapshot={context.snapshot_date!} /></>}</div><Copilot context={context} onResult={value => { if (value.resolved_identity && value.diagnosis) { setResult(value); setError(""); } }} /></div></>;
}
