import Link from "next/link";
import type { ReactNode } from "react";
import type { CopilotResult, Metric } from "../lib/contracts";
import { label, metricValue, compactMetric } from "../lib/presentation";

export function Shell({ children, detail = false }: { children: ReactNode; detail?: boolean }) {
  return <div className="app-shell"><aside className="sidebar"><Link href="/" className="brand"><span className="brand-mark">O<span>·</span></span><span>OVERDUE PO<small>COPILOT</small></span></Link><div className="nav-caption">采购工作空间</div><nav aria-label="主导航"><Link href="/" className={!detail ? "nav-item active" : "nav-item"}><span>▦</span> 超期订单工作台</Link><div className={detail ? "nav-item active" : "nav-item muted"}><span>◫</span> 订单诊断与决策</div></nav><div className="sidebar-note"><span className="dot" /> 只读分析环境<p>建议有依据，操作由人决定。</p><small>Synthetic enterprise data</small></div></aside><div className="workspace"><header className="topbar"><span>采购运营 <span className="slash">/</span> {detail ? "订单分析" : "工作台"}</span><span className="demo-chip">DEMO · 合成数据</span></header>{children}<footer>Overdue PO Copilot <span>确定性指标 · 规则诊断 · 有据可查</span></footer></div></div>;
}
export function Badge({ code }: { code: string }) {
  const tone = ["COMPLETED", "DIAGNOSED", "DECIDED", "AVAILABLE"].includes(code) ? "good" : ["FAILED", "NOT_FOUND"].includes(code) ? "bad" : ["UNRESOLVED", "NOT_EVALUABLE", "PARTIAL", "NEEDS_CLARIFICATION"].includes(code) ? "warn" : "neutral";
  return <span className={`badge ${tone}`}>{label(code)} <small>{code}</small></span>;
}
export function Loading({ text = "正在读取采购数据…" }: { text?: string }) { return <div className="loading" role="status"><span className="spinner" />{text}</div>; }
export function ErrorBox({ message, retry }: { message: string; retry?: () => void }) { return <div className="error-box" role="alert"><strong>暂时无法完成请求</strong><p>{message}</p>{retry && <button className="secondary" onClick={retry}>重新加载</button>}</div>; }
export function MetricCard({ metric }: { metric: Metric }) { const compact = compactMetric(metric), full = metricValue(metric); return <div className="metric"><span>{label(metric.name)}</span><strong className={metric.value === null ? "unavailable" : ""} title={full}>{compact}</strong><small>{metric.value === null ? `NOT COMPUTABLE · ${label(metric.availability)}` : metric.unit}</small>{compact !== full && <details className="exact-number"><summary>展开精确值</summary><code>{full}</code></details>}{metric.availability !== "AVAILABLE" && <span className="metric-state">{label(metric.availability)}</span>}</div>; }
export function ResultCards({ result }: { result: CopilotResult }) {
  const diagnosis = result.diagnosis, decision = result.decision;
  const specGap = result.limitations.some(item => item.includes("DC-16"));
  return <><section className="panel" id="diagnosis"><div className="section-heading"><div><span className="eyebrow">02 / DIAGNOSIS</span><h2>诊断原因</h2></div>{diagnosis && <Badge code={diagnosis.status} />}</div>{diagnosis?.primary_reason ? <h3 className="reason-title">{label(diagnosis.primary_reason)}</h3> : <div className="notice">{diagnosis?.status === "NOT_ELIGIBLE" ? "当前订单不满足诊断资格 / Not applicable" : result.status === "FAILED" ? "分析未完成，未获得诊断结果" : "Insufficient evidence / diagnosis unresolved"}<br /><span>当前尚无确定主原因，不将证据不足解释为业务结论。</span></div>}{diagnosis && <><p className="source-line">来源规则 {diagnosis.primary_rule_id ?? "未匹配"} · {diagnosis.primary_rule_version ?? "—"}</p><div className="signal-list">{diagnosis.supporting_signals.map(signal => <p key={signal}><span>↳</span> {label(signal)}</p>)}</div></>}</section>
    <section className="panel" id="decision"><div className="section-heading"><div><span className="eyebrow">03 / DECISION</span><h2>建议动作</h2></div>{decision && <Badge code={decision.status} />}</div>{decision?.actions.length ? <>{decision.actions.map(action => <div className="action-row" key={action.action_code}><span className="action-icon">↗</span><div><h3>{label(action.action_code)}</h3><p>处理方 / 沟通对象：{label(action.owner_role)}</p></div></div>)}<p className="source-line">{decision.rule_id} · {decision.rule_version}</p></> : <div className="notice">{specGap ? "Decision specification incomplete" : "当前没有确定的采购动作"}<br /><span>{specGap ? "售后正式处置规格 DC-16 尚未完成，不补充取消或保留建议。" : "请先查看证据与规则限制。"}</span></div>}<p className="contract-note">Required checks：当前公开 API 未提供逐项检查结果；此处不推测“已通过”。</p><div className="readonly-note">仅为只读建议 · 未执行取消、改期或任何采购操作</div></section></>;
}
export function Evidence({ result, snapshot }: { result: CopilotResult; snapshot: string }) {
  return <details className="panel evidence" id="evidence"><summary><span><span className="eyebrow">EVIDENCE & TRACE</span><strong>查看证据与规则限制</strong></span><span className="muted">{result.evidence_references.length} 项引用 ＋</span></summary><p className="source-line">Dataset snapshot · {snapshot}</p><div className="reference-list">{result.evidence_references.map(ref => <div key={ref.reference_id}><span className="reference-tag">{ref.source}</span><div><strong>{ref.label}</strong><p>{ref.version_date ?? ref.snapshot_date} {ref.rule_version && `· v${ref.rule_version}`}</p><code>{ref.version_id ?? ref.reference_id}</code></div></div>)}</div><h3>数据 / 规则限制</h3><ul className="limitations">{result.limitations.map((item, i) => <li key={i}>{label(item)}</li>)}</ul><p className="contract-note">参考项目、最大预测贡献项目均不直接表示责任项目。执行引用仅用于本次关联，不是持久化 Trace 链接。</p><code>{result.execution_reference ?? result.request_id}</code></details>;
}
