PATTERNS = (
    "TRIAL",
    "DEMAND_REDUCTION",
    "DEMAND_DELAY",
    "DEMAND_MIXED",
    "CUSTOMER_SIDE_PROJECT_OBSOLESCENCE",
    "AFTER_SALES",
    "STOCKPILE",
    "INTERNAL_SIDE_PROJECT_OBSOLESCENCE",
)

MASS_PATTERNS = PATTERNS[1:]

PATTERN_CAUSE = {
    "TRIAL": "TRIAL",
    "DEMAND_REDUCTION": "DEMAND_ADJUSTMENT",
    "DEMAND_DELAY": "DEMAND_ADJUSTMENT",
    "DEMAND_MIXED": "DEMAND_ADJUSTMENT",
    "CUSTOMER_SIDE_PROJECT_OBSOLESCENCE": "PROJECT_OBSOLESCENCE",
    "AFTER_SALES": "AFTER_SALES",
    "STOCKPILE": "STOCKPILE",
    "INTERNAL_SIDE_PROJECT_OBSOLESCENCE": "PROJECT_OBSOLESCENCE",
}

PATTERN_SUBTYPE = {
    "TRIAL": "NONE",
    "DEMAND_REDUCTION": "REDUCTION",
    "DEMAND_DELAY": "DELAY",
    "DEMAND_MIXED": "MIXED",
    "CUSTOMER_SIDE_PROJECT_OBSOLESCENCE": "NONE",
    "AFTER_SALES": "NONE",
    "STOCKPILE": "NONE",
    "INTERNAL_SIDE_PROJECT_OBSOLESCENCE": "NONE",
}

PATTERN_DEMAND_CHANGE = {
    "TRIAL": "NONE",
    "DEMAND_REDUCTION": "REDUCTION",
    "DEMAND_DELAY": "DELAY",
    "DEMAND_MIXED": "MIXED",
    "AFTER_SALES": "NONE",
    "STOCKPILE": "NONE",
    "INTERNAL_SIDE_PROJECT_OBSOLESCENCE": "NONE",
}

PATTERN_LIFECYCLE = {
    "DEMAND_REDUCTION": "MASS_PRODUCTION",
    "DEMAND_DELAY": "MASS_PRODUCTION",
    "DEMAND_MIXED": "MASS_PRODUCTION",
    "CUSTOMER_SIDE_PROJECT_OBSOLESCENCE": "EOL",
    "AFTER_SALES": "EOL",
}

PATTERN_RESPONSIBILITY = {
    "TRIAL": "MPM",
    "CUSTOMER_SIDE_PROJECT_OBSOLESCENCE": "CUSTOMER_SIDE",
    "INTERNAL_SIDE_PROJECT_OBSOLESCENCE": "INTERNAL_SIDE",
}

PATTERN_EXPECTED_ACTION = {
    "TRIAL": "待MPM确认处理",
    "CUSTOMER_SIDE_PROJECT_OBSOLESCENCE": "沟通客户处理呆滞",
    "INTERNAL_SIDE_PROJECT_OBSOLESCENCE": "沟通事业部处理呆滞",
}
